<?php

namespace App\Faker;

use Faker\Provider\Base;

class SkillsProvider extends Base
{
    protected static $skills = [
        'Laravel',
        'Flutter',
        'Hard Working',
        'Team Player',
        'Problem Solving',
        'Communication',
        'JavaScript',
        'PHP',
        'Python',
        'Project Management',
        'React.js',
        'Writing',
        'Vue.js',
        'CSS',
        'HTML',
        'SQL',
        'NoSQL',
        'Git',
        'GitHub',
        'RESTful APIs',
        'GraphQL',
        'Docker',
        'Kubernetes',
        'AWS',
        'Azure',
        'Google Cloud',
        'CI/CD',
        'Unit Testing',
        'Integration Testing',
        'TDD',
        'BDD',
        'Agile Methodologies',
        'Scrum',
        'Kanban',
        'Leadership',
        'Time Management',
        'Critical Thinking',
        'Creativity',
        'Adaptability',
        'Attention to Detail',
        'Customer Service',
        'Networking',
        'Linux',
        'Windows Server',
        'MacOS',
        'Mobile Development',
        'Responsive Design',
        'SEO',
        'Content Management',
        'WordPress',
        'Joomla',
        'Drupal',
        'Magento',
        'Shopify',
        'E-commerce',
        'Digital Marketing',
        'Social Media',
        'Analytics',
        'Big Data',
        'Machine Learning',
        'Artificial Intelligence',
        'Data Science',
        'Data Visualization',
        'Business Intelligence',
        'DevOps',
        'SaaS',
        'PaaS',
        'IaaS',
        'Microservices',
        'API Development',
        'Backend Development',
        'Frontend Development',
        'Full Stack Development',
        'Software Architecture',
        'System Design',
        'Database Design',
        'Security',
        'Penetration Testing',
        'Cryptography',
        'Blockchain',
        'IoT',
        'AR/VR',
        'Game Development',
        'UI/UX Design',
        'Graphic Design',
        'Video Editing',
        'Audio Editing',
        'Photography',
        'Public Speaking',
        'Negotiation',
        'Sales',
        'Marketing',
        'Finance',
        'Accounting',
        'Human Resources',
        'Legal',
        'Compliance',
        'Risk Management',
        'Supply Chain Management',
        'Logistics',
        'Operations Management',
        'Quality Assurance',
        'Customer Relationship Management',
    ];

    public function skill()
    {
        return static::randomElement(static::$skills);
    }
}
